% Given a list of comparators, a matrix (or column vector) to permute, and 
% a list of swap_amt values, create a version of the matrix that has been
% generated by applying the doubly-stochastic matrix associated to the 
% list of comparators and swap_amt values. 
function A = sn_permute_col(A, comparator_list, swap_amt_list)
    if size(comparator_list,1) ~= length(swap_amt_list)
        fprintf('Error: number of comparators and swap_amts do not match.\n');
        return
    end

    num_perm = length(swap_amt_list);
    
    for i = 1:num_perm
        first_row = A(:,comparator_list(i,1));
        second_row = A(:,comparator_list(i,2));
        swap_amt = swap_amt_list(i);
        
        A(:,comparator_list(i,1)) = swap_amt * first_row + ...
                                               (1-swap_amt) * second_row;
        A(:,comparator_list(i,2)) = (1-swap_amt) * first_row + ...
                                               swap_amt * second_row;
    end